source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EEJSelectMenu_Example', :exclusive => true do
  pod 'EEJSelectMenu', :path => '../'
end

target 'EEJSelectMenu_Tests', :exclusive => true do
  pod 'EEJSelectMenu', :path => '../'

  
end
